
# Example: Hello World App with Antrea Service LoadBalancer/EgressIP different L3 network via BGP
# Deployment hello with 3x pods
# Service type LoadBalancer (Antrea)
# Antrea External IP Pool
# Antrea Egress

---
# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello-world
  name: hello-world
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-world
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      restartPolicy: Always
      containers:
      - image: rancher/hello-world
        imagePullPolicy: Always
        name: hello-world
        ports:
        - containerPort: 80
          protocol: TCP
          name: http

---
# Service type LoadBalancer (Antrea)
apiVersion: v1
kind: Service
metadata:
  name: hello-world
  namespace: default
  annotations:
    service.antrea.io/external-ip-pool: "hello-world"
spec:
  selector:
    app: hello-world
  loadBalancerIP: "10.10.235.33"
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer

---
# Antrea ExternalIPPool (Different L3 subnet)
apiVersion: crd.antrea.io/v1beta1
kind: ExternalIPPool
metadata:
  name: hello-world
spec:
  ipRanges:
  - start: 10.10.235.33
    end: 10.10.235.39
  nodeSelector: {}

---
# Antrea Egress
apiVersion: crd.antrea.io/v1beta1
kind: Egress
metadata:
  name: hello-world
spec:
  appliedTo:
    podSelector:
      matchLabels:
        app: hello-world
  egressIP: 10.10.235.34
  externalIPPool: hello-world
