#
# Example: MSSQL single container + PVC iSCSI RWO (Read/Write Once).
# Only one container attach the iSCSI LUN for R/W.
#

# PV
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mssql-data-pv
  namespace: mssql
spec:
  persistentVolumeReclaimPolicy: Delete
  storageClassName: standard
  claimRef:
    name: mssql-data-pvc
    namespace: mssql
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  iscsi:
    targetPortal: 192.168.10.13
    iqn: "iqn.2018-02.mylab.net:lun1"
    lun: 1
    fsType: xfs
    readOnly: false
    chapAuthDiscovery: false
    chapAuthSession: false


# PVC
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mssql-data-pvc
  namespace: mssql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""
  volumeName: mssql-data-pv

# Service
---
apiVersion: v1
kind: Service
metadata:
  name: mssql
  namespace: mssql
spec:
  type: ClusterIP
  selector:
    app: mssql
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
      name: tcpsql

# Deployment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mssql
  namespace: mssql
  labels:
    app: mssql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mssql
  template:
    metadata:
      labels:
        app: mssql
    spec:
      securityContext:
        fsGroup: 10001
      restartPolicy: Always
      containers:
        - name: mssql
          image: mcr.microsoft.com/mssql/server:2019-latest
          ports:
            - containerPort: 1433
              name: tcpsql
          env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: MSSQL_ENABLE_HADR
              value: "1"
            - name: MSSQL_AGENT_ENABLED
              value: "1"
            - name: MSSQL_SA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mssql
                  key: MSSQL_SA_PASSWORD
          volumeMounts:
            - name: mssql-data
              mountPath: "/mssql/data"
      volumes:
      - name: mssql-data
        persistentVolumeClaim:
          claimName: mssql-data-pvc