
# Example: FRR config for upstream BGP router
# FRR config for upstream BGP router (all worker nodes)

---
# FRR config for upstream BGP router
apiVersion: frrk8s.metallb.io/v1beta1
kind: FRRConfiguration
metadata:
  name: routerupstream
  namespace: frr
spec:
  bgp:
    routers:
    - asn: 64500
      neighbors:
      - address: 10.63.16.2
        asn: 64500
        toAdvertise:
          allowed:
            mode: all
  nodeSelector:
    matchLabels:
      node-role.kubernetes.io/worker: "worker"