#
# Example: Hello World.
# Create the Deployment 3 pods.
# Create the Service
# Create the Nginx Ingress hello.192-168-31-101.sslip.io
# Create the Antrea EgressIP 192.168.31.101 
#

---
# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello-world
  name: hello-world
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-world
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: hello-world
        team: rocket
    spec:
      restartPolicy: Always
      containers:
      - image: rancher/hello-world
        imagePullPolicy: Always
        name: hello-world
        ports:
        - containerPort: 80
          protocol: TCP
          name: http

---
# Service
apiVersion: v1
kind: Service
metadata:
  name: hello-world
  namespace: default
spec:
  ports:
  - port: 80
    name: http
    protocol: TCP
    targetPort: 80
  selector:
    app: hello-world

---
# Ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-ingress
  namespace: default
spec:
  rules:
  - host: hello.192-168-31-101.sslip.io
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: hello-world
            port:
              number: 80

---
# External IP Pool (Antrea CNI)
apiVersion: crd.antrea.io/v1alpha2
kind: ExternalIPPool
metadata:
  name: prod-external-ip-pool
spec:
  ipRanges:
  - start: 192.168.31.100
    end: 192.168.31.150
  - cidr: 192.168.31.0/24
  nodeSelector: {}
#    matchLabels:
#    network-role: egress-gateway

---
# Egress (Antrea CNI)
apiVersion: crd.antrea.io/v1alpha2
kind: Egress
metadata:
  name: egress-prod-hello
spec:
  appliedTo:
#    namespaceSelector:
#      matchLabels:
#        env: prod
    podSelector:
      matchLabels:
        app: hello-world
  egressIP: 192.168.31.101
  externalIPPool: prod-external-ip-pool
#status:
#  egressNode: node01
