---
# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello-world
  name: hello-world
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-world
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      restartPolicy: Always
      containers:
      - image: rancher/hello-world
        imagePullPolicy: Always
        name: hello-world
        ports:
        - containerPort: 80
          protocol: TCP
          name: http

---
# Service
apiVersion: v1
kind: Service
metadata:
  name: hello-world
  namespace: default
  annotations:
    metallb.universe.tf/ip-allocated-from-pool: first-pool
spec:
  ports:
  - port: 80
    name: http
    protocol: TCP
    targetPort: 80
  selector:
    app: hello-world
  type: LoadBalancer
  loadBalancerIP: "10.10.235.33"

---
# External IP Pool
apiVersion: crd.antrea.io/v1beta1
kind: ExternalIPPool
metadata:
  name: prod-external-ip-pool
spec:
  ipRanges:
  - start: 10.10.235.41
    end: 10.10.235.50
  nodeSelector: {}

---
# Egress
apiVersion: crd.antrea.io/v1beta1
kind: Egress
metadata:
  name: egress-prod-hello
spec:
  appliedTo:
    podSelector:
      matchLabels:
        app: hello-world
  egressIP: 10.10.235.43
  externalIPPool: prod-external-ip-pool

